version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14.2
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test:unit
      - run: npm run test:e2e
      - run: git checkout -b gh-pages
      - run: npm run build
      - run: sed -i 's/\/dist/# \/dist/' .gitignore
      - run: git add dist && git commit -m "dist subtree commit"
      - run: git subtree push --prefix dist origin gh-pages
      #- run: deleta branch gh-pages
