version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14.2-browsers
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-
      # - run: npm install
      - run: npm ci

      - save_cache:
          paths:
            # - node_modules
            - ~/.npm
            - ~/.cache
          key: v3-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test:unit
      - run: npm run test:e2e
      - run:
          command: |
            git checkout -b gh-pages
            npm run build
            sed -i 's/\/dist/# \/dist/' .gitignore
            git config user.email 'maurogadelhaa@gmail.com'
            git config user.name 'Mauro Gadelha [CI]'
            git add dist && git commit -m "[skip ci]dist subtree commit"
            git push origin --delete gh-pages
            git subtree push --prefix dist origin gh-pages
