version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14.2-browsers
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-
      
      - run: npm ci

      - save_cache:
          paths:
            # - node_modules
            - ~/.npm
            - ~/.cache
          key: v3-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test:unit
      - run: npm run test:e2e
      
      - run:
          name: deploy
          command: |
            npm run build
            now dist -A ../now.json -t ${NOW_TOKEN}
